"""Delete flight model

Revision ID: c4a9b17a57cc
Revises: 2e6f6a473542
Create Date: 2024-08-25 16:20:57.202697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4a9b17a57cc'
down_revision: Union[str, None] = '2e6f6a473542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flights_id', table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('depature_city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('arrival_city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('depature_time', mysql.DATETIME(), nullable=True),
    sa.Column('arrival_time', mysql.DATETIME(), nullable=False),
    sa.Column('flight_duration', mysql.FLOAT(), nullable=True),
    sa.Column('airline', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_flights_id', 'flights', ['id'], unique=False)
    # ### end Alembic commands ###
