"""Change Flight model

Revision ID: f74550442ce6
Revises: 8c4232fb3186
Create Date: 2024-08-27 20:38:37.060347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f74550442ce6'
down_revision: Union[str, None] = '8c4232fb3186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('time', sa.Time(), nullable=False))
    op.alter_column('flights', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flights', 'date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    op.drop_column('flights', 'time')
    # ### end Alembic commands ###
